# Generated by Django 3.2.12 on 2022-04-01 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rateMyProf', '0001_initial'),
        ('main', '0003_auto_20220401_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rateMyProf.professor'),
        ),
        migrations.DeleteModel(
            name='Professor',
        ),
    ]
