# Generated by Django 3.2.12 on 2022-04-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_course_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='credit',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=100),
        ),
    ]
