# Generated by Django 3.2.12 on 2022-04-01 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220401_1024'),
        ('rateMyProf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='finalRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.TextField()),
                ('attendance', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('grade', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('course', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='finalRatingUser', to='main.course')),
                ('professor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='finalRatingprof', to='rateMyProf.professor')),
            ],
        ),
    ]
