# Generated by Django 3.2.12 on 2022-04-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rateMyProf', '0003_rating_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='comment',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
