# Generated by Django 3.2.12 on 2022-04-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rateMyProf', '0004_professor_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='email',
            field=models.EmailField(blank=True, max_length=100),
        ),
    ]
