# Generated by Django 3.2.12 on 2022-04-03 13:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rateMyProf', '0005_alter_professor_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='comment',
        ),
        migrations.AddField(
            model_name='rating',
            name='comment',
            field=models.TextField(default='No Comment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
