# Generated by Django 3.2.12 on 2022-04-03 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rateMyProf', '0007_auto_20220403_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='course',
        ),
    ]
