# Generated by Django 3.2.12 on 2022-04-03 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_course_note'),
        ('rateMyProf', '0008_remove_rating_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='course', to='main.course'),
        ),
    ]
