# Generated by Django 3.2.12 on 2022-04-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rateMyProf', '0009_rating_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='phone',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
